### ISSUE TITLE
Error compiling in a NextJs project

### ISSUE THREAD

**Issue by EctordAniel** [cloudinary/cloudinary-js-streaming#10]
Hi.
I get the following error when trying to compile my react app when I try to import the modules: initLiveStream, attachCamera, detachCamera from @cloudinary/js-streaming.
And I really don't know how to fix it

```
ReferenceError: self is not defined
    at Module../node_modules/whatwg-fetch/fetch.js (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:20303:38)
    at __webpack_require__ (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:30:30)
    at Module../src/stream.js (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:20975:70)
    at __webpack_require__ (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:30:30)
    at Module../src/index.js (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:20947:65)
    at __webpack_require__ (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:30:30)
    at Object.0 (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:21432:18)
    at __webpack_require__ (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:30:30)
    at \node_modules\@cloudinary\js-streaming\dist\js-streaming.js:94:18
    at \node_modules\@cloudinary\js-streaming\dist\js-streaming.js:97:10
    at webpackUniversalModuleDefinition (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:3:20)
    at Object.<anonymous> (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

    Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (\node_modules\@cloudinary\js-streaming\dist\js-streaming.js:116:9)
```

This would be my packaje.json:
```
{
  "name": "next-stream",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@cloudinary/js-streaming": "^1.2.0",
    "next": "9.4.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-player": "^2.3.1"
  }
}
```

**Comment by eyalktCloudinary** [comment]
Hey @EctordAniel, Could you elaborate on where are you trying to import these modules? I'm asking because `self` is probably referring to the `window` object, which is [only relevant on the front end](https://stackoverflow.com/a/46940797). Could you try importing them at one of your front-end files? (possibly one of your React components)

**Comment by EctordAniel** [comment]
Hello, I already solved it.

I was trying to import it into the index.js of my pages folder in my NextJS project.
And I think the problem was because NextJS was trying to render my component on the server.
But I managed to fix it with the following code.

```
  let initLiveStream, attachCamera, detachCamera

  useEffect(() => {
    if(typeof window !== undefined){
      const Cloudinary = require('@cloudinary/js-streaming');
      initLiveStream = Cloudinary.initLiveStream;
      attachCamera = Cloudinary.attachCamera;
      detachCamera = Cloudinary.detachCamera;
    }
  }, [])
```
